const mockImages = [
  { path: "/gallery/1.png", category: "Простые" },
  { path: "/gallery/2.png", category: "Простые" },
  { path: "/gallery/3.png", category: "Многоуровневые" },
  { path: "/gallery/4.png", category: "Многоуровневые" },
  { path: "/gallery/5.png", category: "Комбинированные" },
  { path: "/gallery/6.png", category: "Комбинированные" },
  { path: "/gallery/7.png", category: "Тканевые" },
  { path: "/gallery/8.png", category: "Тканевые" },
  { path: "/gallery/9.png", category: "Теневой еврокраб" },
  { path: "/gallery/10.png", category: "Теневой еврокраб" },
  { path: "/gallery/11.png", category: "Фотопечать" },
  { path: "/gallery/12.png", category: "Фотопечать" },
  { path: "/gallery/13.png", category: "«Парящие потолки»" },
  { path: "/gallery/14.png", category: "«Парящие потолки»" },
  { path: "/gallery/15.png", category: "Шумоизоляция" },
  { path: "/gallery/16.png", category: "Шумоизоляция" },
  { path: "/gallery/17.png", category: "С подсветкой" },
  { path: "/gallery/18.png", category: "С подсветкой" },
  { path: "/gallery/19.png", category: "Цветные" },
  { path: "/gallery/20.png", category: "Цветные" },
  { path: "/gallery/21.png", category: "Простые" },
  { path: "/gallery/22.png", category: "Простые" },
  { path: "/gallery/23.png", category: "Простые" },
  { path: "/gallery/24.png", category: "Простые" },
  { path: "/gallery/25.png", category: "Простые" },
  { path: "/gallery/26.png", category: "Простые" },
  { path: "/gallery/27.png", category: "Простые" },
  { path: "/gallery/28.png", category: "Простые" },
  { path: "/gallery/29.png", category: "Простые" },
  { path: "/gallery/30.png", category: "Простые" },
  { path: "/gallery/31.png", category: "Простые" },
  { path: "/gallery/32.png", category: "Простые" },
  { path: "/gallery/33.png", category: "Простые" },
  { path: "/gallery/34.png", category: "Простые" },
  { path: "/gallery/35.png", category: "Простые" },
  { path: "/gallery/36.png", category: "Простые" },
];

export default mockImages;
