export {
    ACTION_SETTINGS_CHANGE,
    ACTION_SETTINGS_REMOVE,
    ACTION_FEEDBACK_CHANGE,
    ACTION_FEEDBACK_REMOVE,
    ACTION_PICTURES_CHANGE,
    ACTION_PICTURES_REMOVE,
    ACTION_PICTURES_ADD,
} from './reducer/action-types';

export { reducer } from './reducer';
